# Makefile for dumpfidomsg Internet/FidoNet gateway
# Copyright (c) 1993-1997 by Eugene G. Crosser

INCDIR = iflib

include CONFIG

IFLIBDEFINES =	-DDEBUGFILE=\"${DEBUGFILE}\" \
		-DLOGFILE=\"${LOGFILE}\" \
		-DCONFIGFILE=\"${CONFIGFILE}\" \
		-DMAPTABDIR=\"${MAPTABDIR}\" \
		-DPUBDIR=\"${PUBDIR}\" \
		-DMAILLOG=${MAILLOG}

DEFINES = -DMAILLOG=${MAILLOG} \
		${OPTS} ${IFLIBDEFINES}

OBJIFLIB = xutil.o lutil.o hdr.o rdconfig.o lhash.o charset.o rfcdate.o \
		   falists.o ftn.o bread.o rfcaddr.o getheader.o mime.o matchaka.o \
		   crc.o gettime.o parsedate.tab.o

OBJDUMP = version.o iftoss.o \
		getmessage.o mkrfcmsg.o rfcmsg.o \
		msgflags.o areas.o backalias.o \
		charconv.o charconv_jp.o charconv_hz.o charconv_utf.o

SRCS = $(patsubst %.o,%.c,$(OBJDUMP))
HDRS = areas.h mkrfcmsg.h charconv.h charconv_jp.h charconv_hz.h
OTHER = README.md Makefile
ALL = dumpfidomsg

UTLIB = iflib/utlib.a

.c.o:
	${CC} -c ${CFLAGS} ${INCLUDES} ${DEFINES} $< -o $@

all:	${ALL}

install: all
	${INSTALL} -s $(if $(OWNER),-o) ${OWNER} $(if $(GROUP),-g) ${GROUP} -m ${MODE} dumpfidomsg ${BINDIR}
	${INSTALL} -d ${MAPTABDIR}
	${INSTALL} -m ${MANMODE} maptabs/* ${MAPTABDIR}

clean:
	rm -f *.o iflib/*.o core ${ALL} iflib/parsedate.tab.c iflib/needed.h version.c Makefile.bak $(UTLIB)

iflib/parsedate.tab.c: iflib/parsedate.y
	${YACC} -b iflib/parsedate $<

$(UTLIB): $(patsubst %,iflib/%,$(OBJIFLIB))
	${AR} r $@ $?
	${RANLIB} $@

iflib/needed.h:
	(for f in ${NEEDED} ;do BASE=`basename $$f .o`; BASE=\"$${BASE}.h\" ; \
	echo "#include $${BASE}"; done) > $@

dumpfidomsg:	${OBJDUMP} ${UTLIB}
	${CC} ${LDFLAGS} ${OBJDUMP} ${UTLIB} -o dumpfidomsg ${LIBS}

man:
	${INSTALL} $(if $(MANOWNER),-o) ${MANOWNER} $(if $(MANGROUP),-g) ${MANGROUP} -m ${MANMODE} dumpfidomsg.1 ${MANDIR}/man1/dumpfidomsg.1

version.c:	$(filter-out version.c, ${SRCS}) ${HDRS} CONFIG
	echo 'char *version=${VERSION};' >version.c
	echo 'char *copyright=${COPYRIGHT};' >>version.c
ifdef SOURCE_DATE_EPOCH
	echo "char *reldate=\"$(shell LC_ALL=C date --utc --date="@$(SOURCE_DATE_EPOCH)" +%c)\";" >>version.c
else
	echo "char *reldate=\"`date`\";" >>version.c
endif

depend:	version.c
	@rm -f Makefile.bak; \
	mv Makefile Makefile.bak; \
	sed -e '/^# DO NOT DELETE/,$$d' Makefile.bak >Makefile; \
	${ECHO} '# DO NOT DELETE THIS LINE - MAKE DEPEND RELIES ON IT' \
		>>Makefile; \
	${ECHO} '# Dependencies generated by make depend' >>Makefile; \
	for f in ${SRCS}; \
	do \
		${ECHO} "Dependencies for $$f:\c"; \
		${ECHO} "`basename $$f .c`.o:\c" >>Makefile; \
		for h in `sed -n -e \
			's/^#[ 	]*include[ 	]*"\([^"]*\)".*/\1/p' $$f`; \
		do \
			${ECHO} " $$h\c"; \
			if [ -r $$h ]; \
			then \
				${ECHO} " $$h\c" >>Makefile; \
			else \
				${ECHO} " ${INCDIR}/$$h\c" >>Makefile; \
			fi; \
		done; \
		${ECHO} " done."; \
		${ECHO} "" >>Makefile; \
	done; \
	${ECHO} '# End of generated dependencies' >>Makefile

# DO NOT DELETE THIS LINE - MAKE DEPEND RELIES ON IT
# Dependencies generated by make depend
version.o:
iftoss.o: iflib/lutil.h iflib/config.h iflib/version.h iflib/ftn.h iflib/getheader.h iflib/trap.h iflib/charset.h
getmessage.o: iflib/xutil.h iflib/lutil.h iflib/bread.h iflib/ftn.h iflib/rfcmsg.h mkrfcmsg.h iflib/config.h iflib/crc.h iflib/charset.h
mkrfcmsg.o: iflib/lutil.h iflib/xutil.h mkrfcmsg.h iflib/ftnmsg.h iflib/rfcmsg.h areas.h iflib/falists.h iflib/config.h iflib/needed.h iflib/charset.h charconv.h iflib/mime.h
rfcmsg.o: iflib/xutil.h iflib/lutil.h iflib/rfcmsg.h
msgflags.o: iflib/xutil.h iflib/lutil.h iflib/ftnmsg.h
areas.o: iflib/lutil.h iflib/xutil.h areas.h iflib/config.h iflib/lhash.h iflib/needed.h iflib/charset.h
backalias.o: iflib/xutil.h iflib/lutil.h iflib/ftn.h iflib/needed.h
charconv.o: iflib/config.h iflib/xutil.h iflib/lutil.h iflib/charset.h iflib/mime.h charconv.h
charconv_jp.o: iflib/config.h iflib/xutil.h iflib/lutil.h iflib/charset.h charconv.h charconv_jp.h
charconv_hz.o: iflib/config.h iflib/xutil.h iflib/lutil.h iflib/charset.h charconv.h charconv_hz.h
charconv_utf.o: iflib/lutil.h iflib/charset.h iflib/mime.h charconv.h
# End of generated dependencies
